[tox]
envlist = py{310,311,312,313}, ruff-lint, ruff-check-format, mypy

[testenv]
deps = pytest
commands = pytest {posargs:tests/}

[testenv:ruff-lint]
deps = ruff
commands = ruff check .

[testenv:ruff-check-format]
deps = ruff
commands = ruff format --check --diff .

[testenv:mypy]
deps =
    mypy
    types-click
commands = mypy src/sessionbin
