[tox]
envlist = py314, lint, check-format, typecheck

[testenv]
description = Run tests
deps =
    pytest
    pytest-django
commands = pytest {posargs:tests/}

[testenv:test-cov]
description = Run tests with coverage
deps =
    pytest
    pytest-django
    pytest-cov
commands = pytest --cov=sessionbin --cov-report=term-missing {posargs}

[testenv:lint]
description = Run code linter
skip_install = true
deps = ruff
commands = ruff check .

[testenv:lint-fix]
description = Fix linting errors
skip_install = true
deps = ruff
commands = ruff check --fix .

[testenv:check-format]
description = Check code formatting
skip_install = true
deps = ruff
commands = ruff format --check --diff .

[testenv:format]
description = Format code
skip_install = true
deps = ruff
commands = ruff format .

[testenv:typecheck]
description = Run type checker
basepython = python3.14
deps =
    mypy
    django-stubs
    types-Pygments
commands = mypy src/
