from typing import Protocol


class Storage(Protocol):
    def write_raw(self, slug: str, data: bytes) -> None: ...
    def read_raw(self, slug: str) -> bytes: ...
    def write_fragment(self, slug: str, html: str) -> None: ...
    def read_fragment(self, slug: str) -> str: ...
    def delete(self, slug: str) -> None: ...
