[tox]
envlist = py{310,311,312,313,314}, lint, check-format, typecheck

[testenv]
description = Run tests
deps = pytest
commands = pytest {posargs:tests/}

[testenv:lint]
description = Run code linter
skip_install = true
deps = ruff
commands = ruff check .

[testenv:lint-fix]
description = Fix linting errors
skip_install = true
deps = ruff
commands = ruff check --fix .

[testenv:check-format]
description = Check code formatting
skip_install = true
deps = ruff
commands = ruff format --check --diff .

[testenv:format]
description = Format code
skip_install = true
deps = ruff
commands = ruff format .

[testenv:typecheck]
description = Run type checker
deps =
    mypy
    types-click
commands = mypy src/sessionbin
